<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputType>Library</OutputType>
    <RootNamespace>SubnauticaAutosave</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugType>embedded</DebugType>
    <OutputPath>BepInEx\plugins\SubnauticaAutosave_BZ\</OutputPath>
    <DefineConstants>DEBUG;TRACE;BELOWZERO</DefineConstants>
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
    <LangVersion>7.1</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <OutputPath>BepInEx\plugins\SubnauticaAutosave_BZ\</OutputPath>
    <DefineConstants>BELOWZERO</DefineConstants>
    <WarningLevel>5</WarningLevel>
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
    <LangVersion>7.1</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>C:\Games\Below Zero\BepInEx\core\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>C:\Games\Below Zero\SubnauticaZero_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>C:\Games\Below Zero\SubnauticaZero_Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>C:\Games\Below Zero\BepInEx\core\BepInEx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="LitJson">
      <HintPath>C:\Games\Below Zero\SubnauticaZero_Data\Managed\LitJson.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Nautilus">
      <HintPath>C:\Games\Below Zero\BepInEx\plugins\Nautilus\Nautilus.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Unity.TextMeshPro">
      <HintPath>C:\Games\Below Zero\SubnauticaZero_Data\Managed\Unity.TextMeshPro.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>C:\Games\Below Zero\SubnauticaZero_Data\Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>C:\Games\Below Zero\SubnauticaZero_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>C:\Games\Below Zero\SubnauticaZero_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.InputModule">
      <HintPath>C:\Games\Below Zero\SubnauticaZero_Data\Managed\UnityEngine.InputModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>C:\Games\Below Zero\SubnauticaZero_Data\Managed\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Shared\AutosaveControllerBase.cs">
      <Link>AutosaveControllerBase.cs</Link>
    </Compile>
    <Compile Include="..\Shared\HarmonyPatches.cs">
      <Link>HarmonyPatches.cs</Link>
    </Compile>
    <Compile Include="..\Shared\ModPluginBase.cs">
      <Link>ModPluginBase.cs</Link>
    </Compile>
    <Compile Include="..\Shared\ModOptions.cs">
      <Link>ModOptions.cs</Link>
    </Compile>
    <Compile Include="..\Shared\Translation.cs">
      <Link>Translation.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\Shared\Localization\*.*">
      <Link>Localization\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Target Name="CleanPluginOutput" BeforeTargets="BeforeBuild" Condition="Exists('$(ProjectDir)BepInEx\plugins\SubnauticaAutosave_BZ')">
    <RemoveDir Directories="$(ProjectDir)BepInEx\plugins\SubnauticaAutosave_BZ" ContinueOnError="true" />
  </Target>
  <Target Name="DeployToGameAndZip" AfterTargets="Build">
    <PropertyGroup>
      <GameDir>C:\Games\Below Zero\BepInEx\</GameDir>
      <PluginDir>$(GameDir)plugins\SubnauticaAutosave_BZ\</PluginDir>
      <ZipDir>..\ZIP\BelowZero\</ZipDir>
      <ZipFile>$(ZipDir)$(ProjectName).zip</ZipFile>
    </PropertyGroup>
    <Exec Command="if exist &quot;$(PluginDir)&quot; rmdir /s /q &quot;$(PluginDir)&quot;" />
    <Exec Command="xcopy &quot;$(ProjectDir)BepInEx\plugins\SubnauticaAutosave_BZ\*&quot; &quot;$(PluginDir)&quot; /i /e /r /y /q >nul" />
    <Exec Condition="'$(Configuration)' == 'Release'" Command="if not exist &quot;$(ZipDir)&quot; mkdir &quot;$(ZipDir)&quot;" />
    <Exec Condition="'$(Configuration)' == 'Release'" Command="if exist &quot;$(ZipFile)&quot; del /f /q &quot;$(ZipFile)&quot;" />
    <Exec Condition="'$(Configuration)' == 'Release'" Command="&quot;C:\Program Files\7-Zip\7z.exe&quot; a -mx9 -bso0 -bse2 -bsp0 &quot;$(ZipFile)&quot; &quot;BepInEx\plugins\SubnauticaAutosave_BZ&quot;" WorkingDirectory="$(ProjectDir)" />
  </Target>
</Project>